### PR TITLE
adds StateMod data extractor for parsing .xdd files

### PR DESCRIPTION
**Pull request by thurber**
Here's my initial take on a new xdd parser. Notes:
 * I haven't tested it on a massive amount of files yet and do worry that it may break down at that point
 * It will currently only scale across the CPUs on a single node
 * In theory, on 24ish CPUs this should take 4ish hours to process 10,000 files
 * I have not implemented any anomaly detection yet

### CODE REVIEW

**Comment by thurber** [comment]
Today I ran this utility on the Cube on the 499 xdd files that i found there, which extracted data for 343 structure_ids into their own parquet file. This took 43 minutes using 16 cores. I'm a little disappointed by this speed as it would be about 14 hours for 10,000 files on 16 cores. This would still be an improvement on the original but I believe I can do better.

**Comment by crvernon** [comment]
Have you ran a profiler to see where the bottlenecks are? I'll give this a look tomorrow as well.

**Comment by thurber** [comment]
The bottleneck is the parsing of each xdd file, which takes about a minute per file on one CPU when running in parallel. Incidentally, processing one file in serial is only about 20 seconds (i assume python is delegating to C which is multithreading the I/O on it's own in this case).

**Comment by thurber** [comment]
Finally getting back to this after a while -- just added support to run with command line arguments and cleaned up some other items as discussed with Chris. We think we're parsing the files just about as fast as possible (without getting rid of the sanity checks). So, I'm going to look into implementing MPI so we can spread the work across multiple nodes, in order to get the run time down. This has the added benefit of giving me the opportunity to learn about MPI, which I'll need to know for other IM3 development.

**Review by crvernon — APPROVED** [review]

**Comment by crvernon** [comment]
@thurber feel free to merge when you are ready.

**Comment by thurber** [comment]
@crvernon, i ended up trying to implement MPI, which of course worked great on my local machine but ran into a bunch of errors when trying to run in MPI mode using SLURM on PIC or the Cube. Do you know anyone who is knowledgeable on using SLURM with `mpi4py`? @antonia-had, I see you are using `mpi4py` in your version of the code, but on a machine I'm not familiar with. Have you had luck running `mpi4py` on the Cube, or do you happen to have some advice for an aspiring MPIer? 😸

**Comment by crvernon** [comment]
@thurber Can you point me to your setup on Constance or the CUBE and I'll take a look in the morning.

**Comment by thurber** [comment]
closing in favor of #23

**Pull request closed without merging**
